name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - 2.5
          - 2.6
          - 2.7
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: jruby
            env:
              JRUBY_OPTS: "--debug -X+O"
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
          - os: ubuntu
            ruby: 2.6
            env:
              COVERAGE: PartialSummary,Coveralls
            experimental: true
    
    steps:
    - uses: actions/checkout@v2
    - uses: ioquatix/setup-ruby@master
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 5
      env: ${{matrix.env}}
      run: bundle exec rspec
    
        # - name: Run external tests
        #   timeout-minutes: 5
        #   if: matrix.experimental == false && matrix.os == 'ubuntu'
        #   env: ${{matrix.env}}
        #   run: bundle exec bake external
